spring.application.name=api-gateway
server.port=8080

management.endpoints.web.exposure.include=health,info

# Usuarios

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**

# Catalogo

spring.cloud.gateway.server.webflux.routes[1].id=catalog-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/catalog/**

# Pedidos

spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/orders/**

# Pagamentos

spring.cloud.gateway.server.webflux.routes[3].id=payment-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/payments/**

# Entregas

spring.cloud.gateway.server.webflux.routes[4].id=delivery-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/deliveries/**