spring.application.name=delivery-service
server.port=8085

spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DELIVERY_DB_URL:jdbc:postgresql://localhost:5435/deliveries}
spring.datasource.username=${DELIVERY_DB_USERNAME:deliveries}
spring.datasource.password=${DELIVERY_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.sql.init.mode=never

management.endpoints.web.exposure.include=health,info
